import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';

// Feature: vscode-code-review-extension, Property 8: URL Validation Correctness

/**
 * Property 8: URL Validation Correctness
 * 
 * For any string input, a URL validator should accept it if and only if
 * it is a syntactically valid URL (parseable by the WHATWG URL standard),
 * and should reject all other strings.
 * 
 * Validates: Requirements 6.2
 */

function isValidUrl(urlString: string): boolean {
  try {
    new URL(urlString);
    return true;
  } catch {
    return false;
  }
}

describe('Property 8: URL Validation Correctness', () => {
  it('should accept valid WHATWG URLs and reject invalid strings', () => {
    fc.assert(
      fc.property(
        fc.oneof(fc.webUrl(), fc.string()),
        (input) => {
          const validatorResult = isValidUrl(input);
          
          // Check if the input is actually a valid URL according to WHATWG standard
          let isActuallyValid: boolean;
          try {
            new URL(input);
            isActuallyValid = true;
          } catch {
            isActuallyValid = false;
          }
          
          // The validator result should match the actual validity
          expect(validatorResult).toBe(isActuallyValid);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should accept all valid web URLs generated by fast-check', () => {
    fc.assert(
      fc.property(
        fc.webUrl(),
        (url) => {
          expect(isValidUrl(url)).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should correctly validate a mix of valid and invalid URL patterns', () => {
    fc.assert(
      fc.property(
        fc.oneof(
          fc.webUrl(),
          fc.constant('not-a-url'),
          fc.constant(''),
          fc.constant('http://'),
          fc.constant('://missing-protocol'),
          fc.string().filter(s => !s.includes('://'))
        ),
        (input) => {
          const result = isValidUrl(input);
          
          // Verify the result matches WHATWG URL standard
          let expected: boolean;
          try {
            new URL(input);
            expected = true;
          } catch {
            expected = false;
          }
          
          expect(result).toBe(expected);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should handle edge cases consistently with WHATWG URL standard', () => {
    const edgeCases = [
      'http://localhost',
      'https://127.0.0.1',
      'http://[::1]',
      'ftp://example.com',
      'file:///path/to/file',
      'http://example.com:8080/path?query=value#fragment',
      'not a url',
      '',
      'http://',
      '://no-protocol',
      'example.com', // No protocol
      'http://example .com', // Space in hostname
    ];

    edgeCases.forEach(testCase => {
      const validatorResult = isValidUrl(testCase);
      
      let expectedResult: boolean;
      try {
        new URL(testCase);
        expectedResult = true;
      } catch {
        expectedResult = false;
      }
      
      expect(validatorResult).toBe(expectedResult);
    });
  });
});
